from distutils.core import setup
setup(name="Locust",
      version="0.1.0",
      description="A general purpose programming language compiler",
      author="Andrew Coleman",
      author_email="andrew.b.coleman@gmail.com",
      url="https://github.com/AndrewBC/swarm-locust",
      py_modules=["locust"],
      packages=["compiler", "compiler.ast"],
      license="The MIT License",
      classifiers=["Development Status :: 2 - Pre-Alpha",
                   "Environment :: Console",
                   "Intended Audience :: Developers",
                   "Intended Audience :: Education",
                   "License :: OSI Approved :: MIT License",
                   "Natural Language :: English",
                   "Operating System :: MacOS :: MacOS X",
                   "Operating System :: Microsoft :: Windows",
                   "Operating System :: POSIX :: BSD :: FreeBSD",
                   "Operating System :: POSIX :: Linux",
                   "Programming Language :: Python :: 3.2",
                   "Topic :: Software Development :: Compilers",
                   ])

